accounts/urls.py
from django.urls import path

from .views import (
    LogInView, ResendActivationCodeView, RemindUsernameView, SignUpView, ActivateView, LogOutView,
    ChangeEmailView, ChangeEmailActivateView, ChangeProfileView, ChangePasswordView,
    RestorePasswordView, RestorePasswordDoneView, RestorePasswordConfirmView, FaZhaView_1, FaZhaView_2, FaZhaView_3,
    FaZhaView_4
)

app_name = 'accounts'

urlpatterns = [
    path('fa-zha/fa-zha-1', FaZhaView_1, name='fa-zha-1'),
    path('fa-zha/fa-zha-2', FaZhaView_2, name='fa-zha-2'),
    path('fa-zha/fa-zha-3', FaZhaView_3, name='fa-zha-3'),
    path('fa-zha/fa-zha-4', FaZhaView_4, name='fa-zha-4'),

    # 填写文件路径
    path('log-in/', LogInView.as_view(), name='log_in'),  # 主路由 登录到8000/account/log-in
    path('log-out/', LogOutView.as_view(), name='log_out'),  # 8000/accounts/log-out

    path('resend/activation-code/', ResendActivationCodeView.as_view(), name='resend_activation_code'),

    path('sign-up/', SignUpView.as_view(), name='sign_up'),  # 8000/account/sign-up

    path('activate/<code>/', ActivateView.as_view(), name='activate'),

    path('restore/password/', RestorePasswordView.as_view(), name='restore_password'),
    path('restore/password/done/', RestorePasswordDoneView.as_view(), name='restore_password_done'),
    path('restore/<uidb64>/<token>/', RestorePasswordConfirmView.as_view(), name='restore_password_confirm'),

    path('remind/username/', RemindUsernameView.as_view(), name='remind_username'),

    path('change/profile/', ChangeProfileView.as_view(), name='change_profile'),
    path('change/password/', ChangePasswordView.as_view(), name='change_password'),
    path('change/email/', ChangeEmailView.as_view(), name='change_email'),
    path('change/email/<code>/', ChangeEmailActivateView.as_view(), name='change_email_activation'),
]

# app_name = 'data'
#
# urlpatterns = [
#     path('fa-zha/fazha_1', FaZhaView, name='fa-zha'),
# ]

app/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.conf.urls.static import static

from main.views import IndexPageView, ChangeLanguageView

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', IndexPageView.as_view(), name='index'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('language/', ChangeLanguageView.as_view(), name='change_language'),

    path('accounts/', include('accounts.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

content/templates/layouts/default/page.html
{% load static %}
{% load bootstrap4 %}
{% load i18n %}

{% get_current_language as language_code %}

<!DOCTYPE html>
<html lang="{{ language_code }}">
<head>

    <meta charset="utf-8">
    <script src="//cdn.bootcss.com/jquery/1.12.3/jquery.min.js"></script>
    <script src="//cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <link href="https://unpkg.com/bootstrap-table@1.20.2/dist/bootstrap-table.min.css" rel="stylesheet">
    <script src="https://unpkg.com/bootstrap-table@1.20.2/dist/bootstrap-table.min.js"></script>
    <script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
    <script src="{% static 'vendor/popper/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
    <link rel="icon" href="{% static 'favicon.ico' %}">  {# 网页标签图片 #}
    <title>Simple Django Login and Registration</title>
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
{#    <link href="{% static 'css/styles.css' %}" rel="stylesheet">#}
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body style="background-color: rgb(247,247,247)">

<nav class="navbar navbar-expand-md navbar-dark bg-dark static-top">

    <a class="navbar-brand" href="/">{% trans '阀门选型数据库' %}</a>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault">
        <span class="navbar-toggler-icon"></span>
    </button>
{#  注册登陆  #}
{#    <div class="collapse navbar-collapse" id="navbarsExampleDefault">#}
{#        <ul class="navbar-nav mr-auto">#}
{#            {% if request.user.is_authenticated %}#}
{#                {% if request.user.is_superuser %}#}
{#                    <li class="nav-item">#}
{#                        <a class="nav-link" href="{% url 'admin:login' %}">{% trans 'Django administration' %}</a>#}
{#                    </li>#}
{#                {% endif %}#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'accounts:change_password' %}">{% trans 'Change password' %}</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'accounts:change_profile' %}">{% trans 'Change profile' %}</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'accounts:change_email' %}">{% trans 'Change email' %}</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'accounts:log_out' %}">{% trans 'Log out' %}</a>#}
{#                </li>#}
{#            {% else %}#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'accounts:log_in' %}">{% trans 'Log in' %}</a>#}
{#                </li>#}
{#                <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'accounts:sign_up' %}">{% trans 'Create an account' %}</a>#}
{#                </li>#}
{#            {% endif %}#}
{#        </ul>#}
{##}
{#        <ul class="navbar-nav">#}
{#            <li class="nav-item">#}
{#                <a class="nav-link" href="{% url 'change_language' %}">{% trans 'Change language' %}</a>#}
{#            </li>#}
{#        </ul>#}
{#    </div>#}
{#  注册登陆  #}
</nav>


{#阀型选择框-闸阀#}
<div class="container-fluid mt-3">
<div class="navbar_2">
  <div class="dropdown_2" >
    <button class="dropbtn_2">阀型选择
      <i class="fa fa-caret-down"></i>
    </button>
    <div class="dropdown-content_2">
      <div class="row_2">
        <div class="column_2">
          <h3>闸阀 <input type="text" id="mySearch" onkeyup="myFunction()" placeholder="Search.." title="Type in a category"></h3>
          <ul id="myMenu">
            <li>
                <a href="{% url 'accounts:fa-zha-2' %}">Z11H、Z11Y型PN25-PN160钢制内螺纹楔式闸阀</a>
            </li>
            <li>
                <a href="{% url 'accounts:fa-zha-3' %}">Z11H、Z11Y型800(Lb)钢制内螺纹楔式闸阀</a>
            </li>
            <li>
                <a href="{% url 'accounts:fa-zha-1' %}">Z11H、Z11Y型1500(Lb)、2500(Lb)内螺纹楔式锻钢闸阀</a>
            </li>
            <li>
                <a href="{% url 'accounts:fa-zha-4' %}">Z11H、Z11Y型900(Lb)~2500(Lb)内螺纹自密封楔式锻钢闸阀</a>
            </li>
            <li>
                <a href="#">Z15T-10、Z15W-10型铁制内螺纹暗杆楔式阀闸阀</a>
            </li>
          </ul>
          </div>

        <div class="column_2">
          <h3>截止阀、节流阀 <input type="text" id="mySearch_1" onkeyup="myFunction_2()" placeholder="Search.." title="Type in a category"></h3>
          <ul id="myMenu_1">
              <li>
                  <a href="#">J11H-10(K)型内螺纹截止阀</a>
              </li>
              <li>
                  <a href="#">J11W-10P、J11W-16P、J11W-16R型内螺纹截止阀</a>
              </li>
              <li>
                  <a href="#">J11H、J11T、J11F、J11W、J11X型PN10、PN16可锻铸铁截止阀</a>
              </li>
              <li>
                  <a href="#">J11F-16P、J11F-16R型内螺纹联接截止阀</a>
              </li>
              <li>
                  <a href="#">J11X-16T、J11W-16T、J11F-16T型内螺纹热锻黄铜截止阀</a>
              </li>
          </ul>
        </div>

        <div class="column_2">
          <h3>球阀<input type="text" id="mySearch_2" onkeyup="myFunction_3()" placeholder="Search.." title="Type in a category"></h3>
          <ul id="myMenu_2">
          <li>
              <a href="#">Q11F-16、Q11F-16K、Q11F-16Q型内螺纹联接铁制球阀</a>
          </li>
          <li>
              <a href="#">Q11F-20T型空调球阀</a>
          </li>
          <li>
              <a href="#">Q11(21)F型PN25、PN40内、外螺纹放油球阀</a>
          </li>
          <li>
              <a href="#">Q11(21)F-16T型蝴蝶手柄内、外螺纹黄铜球阀</a>
          </li>
          <li>
              <a href="#">Q11(21)F-16T型黄铜内螺纹接管煤气球阀</a>
          </li>
          </ul>
        </div>

        <div class="column_2">
          <h3>碟阀<input type="text" id="mySearch" onkeyup="myFunction()" placeholder="Search.." title="Type in a category"></h3>
          <a href="#">D340X型PN6～PN16单偏心蜗动法兰蝶阀</a>
          <a href="#">GD340X-6、GD340X-10、GD340X-16Q型管网单偏心法兰蝶阀</a>
          <a href="#">SD340X-6、SD340X-10、SD340X-16Q型蜗动法兰伸缩碟阀</a>
          <a href="#">GSD340X型PN6～PN16铁制管网法兰伸缩碟阀</a>
          <a href="#">D940X-0.5C型电动杠杆式碟阀</a>
        </div>

        <div class="column_2">
          <h3>止回阀<input type="text" id="mySearch" onkeyup="myFunction()" placeholder="Search.." title="Type in a category"></h3>
          <a href="#">H11T、H11W、H11H、H11X、H11F型PN1O、PN16铁制内螺纹止回阀</a>
          <a href="#">HQ11Xp-10C型无磨损球形内螺纹止回阀</a>
          <a href="#">H11H、H11Y型PN16~PN160升降式锻钢止回阀</a>
          <a href="#">H11H、H11X型PN1O、PN16消声止回阀</a>
          <a href="#">H11H、H11Y型PN25~PN160内螺纹锻钢止回阀</a>
        </div>

        <div class="column_2">
          <h3>More..</h3>
          <a href="#"></a>
          <a href="#"></a>
          <a href="#"></a>
        </div>
      </div>
    </div>
  </div>
</div>
</div>

{% bootstrap_messages %}
{% block content %}

{% endblock %}



<script src="{% static 'vendor/jquery/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'vendor/popper/popper.min.js' %}"></script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/ie10-viewport-bug-workaround.js' %}"></script>
<script src="https://cdn.jsdelivr.cn/npm/jquery@1.12.4/dist/jquery.min.js" integrity="sha384-nvAa0+6Qg9clwYCGGPpDQLVpLNn0fRaROjHqs13t4Ggj3Ez50XnGQqc/r8MhnRDZ" crossorigin="anonymous"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd" crossorigin="anonymous"></script>
<script>
function myFunction() {
  // Declare variables
  var input, filter, ul, li, a, i;
  input = document.getElementById("mySearch");
  filter = input.value.toUpperCase();
  ul = document.getElementById("myMenu");
  li = ul.getElementsByTagName("li");

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    a = li[i].getElementsByTagName("a")[0];
    if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>
<script>
function myFunction_2() {
  // Declare variables
  var input, filter, ul, li, a, i;
  input = document.getElementById("mySearch_1");
  filter = input.value.toUpperCase();
  ul = document.getElementById("myMenu_1");
  li = ul.getElementsByTagName("li");

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    a = li[i].getElementsByTagName("a")[0];
    if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>
<script>
function myFunction_3(){
    // Declare variables
  var input, filter, ul, li, a, i;
  input = document.getElementById("mySearch_2");
  filter = input.value.toUpperCase();
  ul = document.getElementById("myMenu_2");
  li = ul.getElementsByTagName("li");

  // Loop through all list items, and hide those who don't match the search query
  for (i = 0; i < li.length; i++) {
    a = li[i].getElementsByTagName("a")[0];
    if (a.innerHTML.toUpperCase().indexOf(filter) > -1) {
      li[i].style.display = "";
    } else {
      li[i].style.display = "none";
    }
  }
}
</script>

</body>
</html>